### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tacuna** [eldruin/tcs3472-rs#1]
In this commit, https://github.com/eldruin/tcs3472-rs/commit/1025eb2a8dba467dd3218af72d256108af51c5eb, you have added a useful function which has not been released yet.

Are there any plans to create a new release?

**Comment by eldruin** [comment]
Sure, I'll prepare a new release.

**Comment by eldruin** [comment]
I have just released version [`0.2.0`](https://crates.io/crates/tcs3472/0.2.0). Closing.
