### ISSUE TITLE
tcs3400

### ISSUE THREAD

**Issue by andresv** [eldruin/tcs3472-rs#3]
Hi, i forked your driver and crated driver for [tcs3400](https://crates.io/crates/tcs3400) which is very similar device.

I would like to share this crate with some org or with somebody so I wouldn't be sole owner. To you happen to know who should I ping?

**Comment by eldruin** [comment]
Hi. Nice work. Sure.
Here are some suggestions:
- You can transfer the driver to the [rust-embedded-community org](https://github.com/rust-embedded-community) (you can keep full permissions) (for that open an issue in the [meta](https://github.com/rust-embedded-community/meta) repo)
- You can give me or someone else permissions to your repo.

**Comment by eldruin** [comment]
The repo was transferred. Closing.
